name: Build and Deploy (Nuxt SSG)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  imported:
    uses: peruibeloko/shared/.github/workflows/nuxt.yml@main
